In [2]:
import numpy as np

In [3]:
my_list=[1,2,3]
arr=np.array(my_list)

In [4]:
arr


array([1, 2, 3])

In [5]:
my_list2=[[1,2,3],[4,5,6],[7,8,9]]
arr2=np.array(my_list2)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(5)

array([0.32566678, 0.85634069, 0.96580808, 0.61936289, 0.61777275])

In [21]:
arr3=np.random.rand(5,5)
arr3

array([[0.72440822, 0.33806254, 0.86916495, 0.75711194, 0.34216692],
       [0.53387252, 0.61888492, 0.08661071, 0.28336485, 0.38951512],
       [0.16511346, 0.04726186, 0.80340996, 0.28319147, 0.56868664],
       [0.93475752, 0.90982024, 0.76263373, 0.1510726 , 0.1990783 ],
       [0.11169511, 0.8583935 , 0.00261684, 0.5700504 , 0.50170253]])

In [16]:
np.random.randn(2)

array([ 0.81867299, -1.49190607])

In [17]:
np.random.randn(2,2)

array([[0.21772525, 1.96623591],
       [0.06776397, 0.42986511]])

In [18]:
np.random.randint(1,100)

90

In [19]:
np.random.randint(1,100,5)

array([87,  5, 77, 61, 63])

In [22]:
arr3.reshape(25)

array([0.72440822, 0.33806254, 0.86916495, 0.75711194, 0.34216692,
       0.53387252, 0.61888492, 0.08661071, 0.28336485, 0.38951512,
       0.16511346, 0.04726186, 0.80340996, 0.28319147, 0.56868664,
       0.93475752, 0.90982024, 0.76263373, 0.1510726 , 0.1990783 ,
       0.11169511, 0.8583935 , 0.00261684, 0.5700504 , 0.50170253])

In [23]:
arr3.reshape(25,1)

array([[0.72440822],
       [0.33806254],
       [0.86916495],
       [0.75711194],
       [0.34216692],
       [0.53387252],
       [0.61888492],
       [0.08661071],
       [0.28336485],
       [0.38951512],
       [0.16511346],
       [0.04726186],
       [0.80340996],
       [0.28319147],
       [0.56868664],
       [0.93475752],
       [0.90982024],
       [0.76263373],
       [0.1510726 ],
       [0.1990783 ],
       [0.11169511],
       [0.8583935 ],
       [0.00261684],
       [0.5700504 ],
       [0.50170253]])

In [24]:
arr3.max()

0.9347575220662425

In [25]:
arr3.min()

0.0026168444846452754

In [26]:
arr3.argmax()

15

In [27]:
arr3.argmin()

22

In [31]:
arr3.shape

(5, 5)

In [29]:
arr3.shape

(5, 5)

In [30]:
arr.dtype

dtype('int32')

Indexing 


In [32]:
arr[0:5]

array([1, 2, 3])

In [33]:
arr[1:]

array([2, 3])

When you change a subset of array, it changes original array as well to save memory


In [34]:
arr+arr

array([2, 4, 6])

In [35]:
arr-arr

array([0, 0, 0])

In [36]:
arr*arr

array([1, 4, 9])

In [37]:
arr/arr

array([1., 1., 1.])

In [38]:
arr-100

array([-99, -98, -97])

In [39]:
0/0

ZeroDivisionError: division by zero

In [43]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229])

In [41]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081])

In [42]:
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [44]:
np.sin(arr)

array([0.84147098, 0.90929743, 0.14112001])

In [45]:
np.min(arr)

1

In [46]:
np.max(arr)

3